{% set version = "0.5" %}

package:
  name: eofetch
  version: {{ version }}

source:
  url: https://github.com/stcorp/eofetch/archive/{{ version }}.tar.gz
  sha256: df3f27215dfa20c35d1c63c268fd6906f5bab7d0a1d33bb019dd5918c0b725ab

build:
  entry_points:
    - eofetch = eofetch.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3
    - pystac-client
    - requests

test:
  imports:
    - eofetch
  commands:
    - pip check
    - eofetch --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stcorp/eofetch
  summary: EOFetch is a python library and command-line tool for easy downloading of EO data products.
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - svniemeijer
